config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :categories
  resources :people do
    member do
      put "like",    to: "people#upvote"
      put "dislike", to: "people#downvote"
    end
    resources :comments
  end
  resources :interests
  resources :groups do
    resources :comments
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'people/type_select', to: 'people#type_select'

end

app/models/person.rb
class Person < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  # has_many :person_users
  # has_many :users, through: :person_users
  has_many :person_groups
  has_many :groups, through: :person_groups
  has_many :comments

  # has_many :listing_categories
  # has_many :categories, through: :listing_categories
  # has_many :listing_interests
  # has_many :interests, through: :listing_interests

  validates :title, presence: true, length: { minimum: 5, maximum: 35 }
  validates :tag_line, presence: true, length:  { minimum: 1, maximum: 160 }
  validates :description, presence: true, length: { minimum: 1, maximum: 1000 }
  validates :user_id, presence: true
  validates :group_ids, presence: true

  mount_uploader :profile_image_url, AvatarUploader




end

app/models/user.rb
class User < ApplicationRecord
  has_many :people
  # has_many :person_users
  # has_many :people, through: :person_users
  has_many :groups, dependent: :destroy
  # has_many :user_interests
  # has_many :interests, through: :user_interests
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader


   def name
     "#{first_name} #{last_name}"
   end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:destroy]

  def index

    if params[:search]
      @people = Person.where(['title like ?', "%#{params[:search]}%"])
    else
      @people = Person.reorder("created_at DESC").page(params[:page]).per_page(25)
    end
    # @people = Person.search(params[:search])
    # @people = Person.reorder("created_at DESC").page(params[:page]).per_page(25)
  end

  def new
    @person = Person.new

  end

  def edit
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    if @person.save
      flash[:success] = "Listing was successfully created"
      redirect_to person_path(@person)
    else
      render 'new'
    end
  end

  def show

  end

  def destroy
    @person.destroy
    flash[:danger] = "Listing was successfully deleted"
    redirect_to people_path
  end

  def update
    if @person.update(person_params)
      flash[:success] = "Listing updated succcessfully"
      redirect_to person_path(@person)
    else
      render 'edit'
    end
  end

  def upvote
    @person = Person.find(params[:id])
    @person.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @person = Person.find(params[:id])
    @person.downvote_by current_user
    redirect_to :back
  end

  private
    def person_params
      params.require(:person).permit(:title,
                                      :tag_line,
                                      :description,
                                      :profile_image_url,
                                      :twitter_url,
                                      :facebook_url,
                                      :linkedin_url,
                                      :instagram_url,
                                      :snapchat_url,
                                      :youtube_url,
                                      :angellist_url,
                                      :medium_url,
                                      :producthunt_url,
                                      :reddit_url,
                                      :twitch_url,
                                      :companions,
                                      :price,
                                      :price_time,
                                      :start_date,
                                      :end_date,
                                      :city,
                                      user_ids: [],
                                      category_ids: [],
                                      interest_ids: [],
                                      group_ids: [])
    end

    def set_person
      @person = Person.find(params[:id])
    end

    def require_same_user
      if current_user != @person.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own OverLink"
        redirect_to root_path
      end
    end

end

app/views/people/_form.html.erb
<%= render 'shared/errors', obj: @person %>
<div class="container">
  <div class="row">
    <%= form_for(@person, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="col-xs-12  col-md-8">
        <div class="form-container-listing">
          <div class="well well-white">
            <div class="form-group">
              <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-3 col-lg-3">
                <%= image_tag @person.profile_image_url.url(:medium), class: "profilePhoto" if @person.profile_image_url? %>
                <%= f.label :upload_profile_photo %>
                <%= f.file_field :profile_image_url, accept: 'image/png,image/gif,image/jpeg,image/jpg' %>
              </div>
              <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-6 col-lg-6">
                <%= f.label :full_name %>
                <%= f.text_field :title, class: "form-control", placeholder: "John Doe", autofocus: true %>
                <br>
                <%= f.label :Short_description_160_characters_max %>
                <%= f.text_area :tag_line, class:  "form-control", placeholder: "Great but pretty average man.", autofocus: false %>
              </div>
            </div>
          </div>

          <div class="well well-white">
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Twitter %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.twitter.com/</span>
                  <%= f.text_field :twitter_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Facebook %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.facebook.com/</span>
                  <%= f.text_field :facebook_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Linkedin %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.linkedin.com/in/</span>
                  <%= f.text_field :linkedin_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Instagram %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.instagram.com/</span>
                  <%= f.text_field :instagram_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Snapchat %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.snapchat.com/add/</span>
                  <%= f.text_field :snapchat_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :YouTube %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.youtube.com/user/</span>
                  <%= f.text_field :youtube_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :AngelList %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.angel.co/</span>
                  <%= f.text_field :angellist_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Medium %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.medium.com/</span>
                  <%= f.text_field :medium_url, rows: 1, class: "form-control", placeholder: "@overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :ProductHunt %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.producthunt.com/</span>
                  <%= f.text_field :producthunt_url, rows: 1, class: "form-control", placeholder: "@overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Reddit %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.reddit.com/user/</span>
                  <%= f.text_field :reddit_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
              <%= f.label :Twitch %>
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3">https://www.twitch.tv/</span>
                  <%= f.text_field :twitch_url, rows: 1, class: "form-control", placeholder: "overlink", autofocus: false %>
              </div>
            </div>
          </div>
        </div>

          <div class="well well-white">
            <div class="form-group">
                  <div class="col-sm-offset-1 col-sm-10 col-md-offset-1 col-md-10 col-lg-10">
                <%= f.label :About %>
                <%= f.text_area :description, rows: 3, class: "form-control", placeholder: "Some words about this person to help other people discover more", autofocus: false %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-md-4">
        <div class="well well-white">
          <% if user_signed_in?  %>
            <div class="title-category"><h4>Add this person to the groups you created:</br>
              <small>If you want to add person to the groups created by other users, you need to go to this group and press "Add a new person to this group"</small>
              <br>
              <small><%= link_to 'Add a new group', new_group_path %></small></h4></div>
              <%= f.collection_check_boxes :group_ids, current_user.groups, :id, :title do |cb| %>
                <ul>
                  <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
                </ul>
             <% end %>
           <% end %>
         </div>
          <% if current_user != @person.user %>
            <% if @person.groups.count == 0 %>
            <% end %>
            <% if @person.groups.count >= 1 %>
              <div class="well well-white">
                <div class="title-category"><h4>Person's groups:</br>
                <small>If you want to deselect person from the group you created, do it here and in the field above.</small>
                <br>
                </h4></div>
                <%= f.collection_check_boxes :group_ids, @person.groups, :id, :title do |cb| %>
                <ul>
                  <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
                </ul>
                <% end %>
                <% if @person.groups.count == 0 %>
                  <h4><small>New person will get a groups after creating.</small></h4>
                <% end %>
              </div>
            <% end %>
          <% end %>
      </div>

      <div class="col-xs-12 col-md-12">
        <div class="well well-white">
          <div class="form-group">
            <div class=" col-sm-12  col-md-12 col-lg-12">
              <div class="btn-submit-listing">
              <%= f.submit class: 'btn btn-primary btn-lg btn-long'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/people/_person.html.erb
<% obj.each do |person| %>
  <div class="container-fluid">
    <div class="row">
      <div class="well well-white">
        <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-6">
            <div class="listing-title">
              <%= image_tag person.profile_image_url.url(:small), class: "profilePhotoThumb" if person.profile_image_url? %>
              <%= link_to person.title, person_path(person), class: "listing-title-text" %>
              <h4><small><%= person.tag_line %></small></h4>
            </div>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-6">
            <% if person.twitter_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://twitter.com/#{person.twitter_url}", class: "fa fa-twitter fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.facebook_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://facebook.com/#{person.facebook_url}", class: "fa fa-facebook fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.linkedin_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://linkedin.com/in/#{person.linkedin_url}", class: "fa fa-linkedin fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.instagram_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://instagram.com/#{person.instagram_url}", class: "fa fa-instagram fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.snapchat_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://snapchat.com/add/#{person.snapchat_url}", class: "fa fa-snapchat fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.youtube_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://youtube.com/user/#{person.youtube_url}", class: "fa fa-youtube fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.angellist_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://angel.co/#{person.angellist_url}", class: "fa fa-angellist fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.medium_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://medium.com/#{person.medium_url}", class: "fa fa-medium fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.producthunt_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://producthunt.com/#{person.producthunt_url}", class: "fa fa-producthunt fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.reddit_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://reddit.com/#{person.reddit_url}", class: "fa fa-reddit fa-2x",  :target => '_blank' %></span>
              <% end %></i>
            <% if person.twitch_url != "" %>
                <i class="icons-paddings"><%= link_to "", "https://twitch.com/#{person.twitch_url}", class: "fa fa-twitch fa-2x",  :target => '_blank' %></span>
              <% end %></i>
          </div>
        </div><hr>
        <div class="row">
          <div class="col-sm-6 col-md-2 col-lg-2">
            <div class="btn-group">
              <%= link_to like_person_path(person), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="fa fa-caret-up">
              <%= person.get_upvotes.size %>
              <% end %>
              <%= link_to dislike_person_path(person), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="fa fa-caret-down">
              <%= person.get_downvotes.size %>
              <% end %>
            </div>
          </div>
          <div class="">
          <div class="col-sm-6 col-md-2 col-lg-2">
            <h5 class="comments_title">
              <%= person.comments.count %> Comments
            </h5>
          </div>
        </div>


        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>OverLink | Edit Person</title>

  </head>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="well well-white">
          <h1 align="center">Edit person profile</h1>
        </div>
      </div>
    </div>
  </div>



<div class="container">
  <div class="row">
<%= render 'form' %>
</div>
</div>

app/views/people/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OverLink | People</title>
  </head>



  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <div class="well well-white">
          <h1 align="center">List of all people</h1>
            <div class="row">
            <%= form_tag people_path, method: :get, class: "navbar-form navbar-left search-form" do %>
              <%= text_field_tag(
                  :search,
                  params[:search],
                  placeholder: "Search by name",
                  class: "form-control"
              ) %>
             <%= submit_tag "Search!", :name => nil, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>




      <div align="center">
        </div>

            <div class="container-fluid">
              <div class="row">
                <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                  <%= render 'person', obj: @people %>
                </div>
              </div>
            </div>

        <div align="center">
      </div>

app/views/people/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>New Person | OverLink</title>
  </head>


  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="well well-white">
          <h1 align="center">OverLink a new Person</h1>
          <h5 align="center">Add new Person</h5>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <%= render 'form' %>
    </div>
  </div>

app/views/people/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @person.title %> | OverLink</title>
  </head>
  <body id="show-listing-body">
    <div class="container">
    <div class="row ">
      <div class="col-md-10 col-md-offset-1 ">
        <div class="well well-white">
          <ul class="listing">
            <div class="row ">
              <div class="col-sm-3 col-md-3 col-lg-3">
                <li><%= image_tag @person.profile_image_url.url(:medium), class: "profilePhoto" if @person.profile_image_url? %></li>
              </div>
              <div class="col-sm-9 col-md-9 col-lg-9">
                <li class="listing-title">
                  <h1 class="person-profile-title"><strong><%= @person.title %></strong></h1>
                </li>
                <li><p><%= @person.tag_line %></p></li>
<br>
                <% if @person.groups.any? %>
                <%= render @person.groups %>
                <% end %>


              </div>
              </div>

              <div class="row ">
                <hr>
                <div class="listing-actions">

                    <li class="list-group-item"><h3><small>About:</small></h3></li>
                    <li class="list-group-item"><p><%= @person.description %></p></li>

                </div>
              </div>
              <div class="row ">
                <hr>
                  <div class="listing-actions">
                    <li class="list-group-item"><h3><small>Social links:</small></h3></li>
                </div>
              </div>
          <div class="row">
            <div class="listing-actions">
              <div class="col-sm-12 col-md-12 col-lg-12">


                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                  <% if @person.twitter_url != "" %><li class="list-group-item">
                      <i class="icons-paddings"><%= link_to "", "https://twitter.com/#{@person.twitter_url}", class: "fa fa-twitter fa-2x",  :target => '_blank' %></span>
                    </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                  <% if @person.facebook_url != "" %><li class="list-group-item">
                      <i class="icons-paddings"><%= link_to "", "https://facebook.com/#{@person.facebook_url}", class: "fa fa-facebook fa-2x",  :target => '_blank' %></span>
                    </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                  <% if @person.linkedin_url != "" %><li class="list-group-item">
                      <i class="icons-paddings"><%= link_to "", "https://linkedin.com/in/#{@person.linkedin_url}", class: "fa fa-linkedin fa-2x",  :target => '_blank' %></span>
                    </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.instagram_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://instagram.com/#{@person.instagram_url}", class: "fa fa-instagram fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.snapchat_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://snapchat.com/add/#{@person.snapchat_url}", class: "fa fa-snapchat fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.youtube_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://youtube.com/user/#{@person.youtube_url}", class: "fa fa-youtube fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.angellist_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://angel.co/#{@person.angellist_url}", class: "fa fa-angellist fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.medium_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://medium.com/#{@person.medium_url}", class: "fa fa-medium fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.producthunt_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://producthunt.com/#{@person.producthunt_url}", class: "fa fa-product-hunt fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.reddit_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://reddit.com/#{@person.reddit_url}", class: "fa fa-reddit fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>
                <div class="col-xs-3 col-sm-2 col-md-1 col-lg-1">
                <% if @person.twitch_url != "" %><li class="list-group-item">
                    <i class="icons-paddings"><%= link_to "", "https://twitch.com/#{@person.twitch_url}", class: "fa fa-twitch fa-2x",  :target => '_blank' %></span>
                  </i></li><% end %>
                </div>

              </div>
          </div>
        </div>





          </ul>
        </div>
      </div>
    </div>


      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="panel panel-default">
            <div class="panel-body">
              <h4><small>Added by:</small></h4>
              <div class="listing-meta-details">
                <small><%= image_tag @person.user.avatar.url(:thumb), class: "profilePhotoThumb" if @person.user.avatar? %>
                  <%= link_to @person.user.name, user_path(@person.user) %>
                                  <%= time_ago_in_words(@person.created_at) %> ago  |
                                  last updated: <%= time_ago_in_words(@person.updated_at) %> </small>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h2>Comments</h2>
              <h3><small>Here you can write something about this person, your thoughts and findings.<br>
                 Also you can suggest other links to this person around the web.</small></h3>
            </div>
          <div class="panel-body">
            <h5 class="comments_title">
              <%= @person.comments.count %> Comments
            </h5>
            <div id="comments">
                <%= render :partial => @person.comments %>
            </div>
            <%= simple_form_for [@person, Comment.new]  do |f| %>
              <div class="field">
                <%= f.text_area :body, class: "form-control" %>
              </div>
              <br>
              <%= f.submit "Add Comment", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>




        <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="listing-actions">
                  <% if user_signed_in? && (current_user == @person.user || current_user.admin?) %>
                      <%= link_to 'Delete this person', person_path(@person), method: :delete,
                                                          data: { confirm: "Are you sure you want to delete this person?"},
                                                          class: "btn btn-xs btn-danger" %>
                    <% end %>
                    <%= link_to 'Edit this person', edit_person_path(@person), class: "btn btn-xs btn-primary" %>
                    <%= link_to 'View all people', people_path, class: "btn btn-xs btn-success" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <!-- </div>
    </div>
  </div> -->
</div>
</body>
</html>