config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :categories
  resources :people do
    member do
      put "like",    to: "people#upvote"
      put "dislike", to: "people#downvote"
    end
    resources :comments
  end
  resources :interests
  resources :groups do
    resources :comments
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'people/type_select', to: 'people#type_select'

end

app/models/group.rb
class Group < ApplicationRecord
  acts_as_votable

  belongs_to :user

  has_many :person_groups
  has_many :people, through: :person_groups
  has_many :category_groups
  has_many :categories, through: :category_groups
  has_many :comments


  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 60 }
  validates :description, presence: true, length: { minimum: 10, maximum: 350 }
  validates :category_ids, presence: true
  validates_uniqueness_of :title

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user, except: [:index, :show]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      flash[:success] = "Group was created succesfully"
      redirect_to groups_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:success] = "Group was updated succcessfully"
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def show
    @group = Group.find(params[:id])
    @person_groups = @group.people.paginate(page: params[:page], per_page: 4)
  end



  private
  def group_params
    params.require(:group).permit(:title, :description, category_ids: [], person_ids: [])
  end

  def set_person
    @group = Group.find(params[:id])
  end

end

app/views/groups/_form.html.erb
<%= render 'shared/errors', obj: @group %>

<div class="container-fluid">
  <div class="row">
  <div class="col-md-12">
    <%= form_for(@group, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="well well-white">
      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2">
          <%= f.label :title %>
        </div>
        <div class="col-md-4">
          <%= f.text_field :title, class: "form-control", placeholder: "Group title (max 60 charachters)", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2  ">
          <%= f.label :description %>
        </div>
        <div class="col-md-4 ">
          <%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Desctiption of a group (max 350 charachters)", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2  ">
          <%= f.label :categories_of_the_group %>
        </div>
        <div class="col-md-4 ">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <ul>
          <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
        </ul>
        <% end %>
      </div>

      </div>


      <div class="form-group">
        <div class="control-label col-md-2 col-md-offset-2  ">
          <%= f.label :people_of_the_group %>
        </div>
        <div class="col-md-4 ">
          <%= f.collection_check_boxes :person_ids, Person.all, :id, :title do |cb| %>
            <ul>
              <%= cb.label(class: "list-group-item list-group-item-on-bg checkbox-inline input_checkbox itme-list") {cb.check_box(class: "list-group-item checkbox ") + cb.text}  %>
            </ul>
          <% end %>
        </div>
      </div>




        <div class="form-group">
          <div class="col-md-offset-4 col-md-12">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
      <% end %>


        <div class="col-md-5 col-md-offset-4">
          [ <%= link_to 'Cancel request and return to groups', groups_path %> ]
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
<span class="badge badge-interest"><%= link_to group.title, group_path(group), class: "badge-text-interest" %></span>

app/views/groups/_groupfull.html.erb
<% obj.each do |category_groups| %>
  <div class="container-fluid">
    <div class="row">
      <div class="well well-white">
        <div class="row">
          <div class="col-sm-12 col-md-5 col-lg-5">
            <div class="listing-title">
              <h4><%= link_to category_groups.title, group_path(category_groups), class: "listing-title-text" %><h4>
              <hr>
              <p><small><%= category_groups.description %></small></p>
              <h5 class="listing-tag-line"><small><%= category_groups.person_ids.count %> people in the group</small></h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OverLink | Edit Group</title>
  </head>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="well well-white">
          <h1 align="center">Edit group</h1>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <%= render 'form' %>
    </div>
  </div>

app/views/groups/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Overlink Groups</title>
  </head>



  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
        <div class="well well-white">
          <h1 align="center">List All Groups</h1>
        </div>
      </div>
    </div>
  </div>




<div class="container">
  <div class="row">
    <!-- <nav class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
      <ul class="list-group">
        <li class="list-group-item">
          <h2 align="center">Popular groups
          </h2>
        </li>
        <li class="list-group-item">
          <span class="badge">257</span>
          Photograpy
        </li>
        <li class="list-group-item">
          <span class="badge">324</span>
          Nightlife
        </li>
      </ul>
    </nav> -->
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
          <ul class="listing">
            <div class="container-fluid">
              <div class="row">
                <% @groups.each do |category_groups| %>
                  <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                    <div class="well well-white">
                      <li class="article-title">
                          <h4 class="group-title">
                          <%= link_to "#{category_groups.title}", group_path(category_groups), class:"group-title" %> <small>by <%= category_groups.user.name %></small>
                          </h4>
                          <h4><small><%= category_groups.people.count %> people in this group</small></h4>
                          <h4><hr>
                          <small>
                          <%= truncate(category_groups.description, length: 100) %>
                          </small></h4>
                      </li>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </ul>

    </div>
  </div>
</div>

app/views/groups/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>OverLink | New Group</title>
  </head>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="well well-white">
          <h1 align="center">Create a new group</h1>
        </div>
      </div>
    </div>
  </div>



<%= render 'form' %>

app/views/groups/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @group.title %> | Overlink</title>
  </head>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="well well-white">
        <h1 align="center"><%= "List of all People in " + @group.title %></h1>
        <h1 align="center"><small><%= @group.description %></small></h1>
        <hr>
        <h4 align="center"><small>Group created by <%= link_to @group.user.name, user_path(@group.user), class: "listing-title-text" %></small></h4>
        <% if user_signed_in? %>
        <%= link_to 'Suggest a Person to this group', new_person_path, class:"btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div align="center">
  <% if user_signed_in? and current_user.admin? %>
    <div class="row">
      <span class="badge edit-category-badge"><%= link_to "Edit Group Info", edit_group_path(@group), class: "edit-category" %></span>
    </div>
  <% end %>
  <%= will_paginate @person_groups %>
    </div>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
            <%= render 'people/person', obj: @person_groups %>
          </div>
        </div>
      </div>
    <div align="center">
  <%= will_paginate @person_groups %>
</div>