config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :categories
  resources :people do
    member do
      put "like",    to: "people#upvote"
      put "dislike", to: "people#downvote"
    end
    resources :comments
  end
  resources :interests
  resources :groups do
    resources :comments
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#index'
  get 'pages/about', to: 'pages#about'



  get 'users/:id' => 'users#show', as: :user
  # get 'signup', to: 'users#new'
  resources :users, except: [:new]
  #
  # get 'login', to: 'sessions#new'
  # post 'login', to: 'sessions#create'
  # delete 'logout', to: 'sessions#destroy'

  get 'people/type_select', to: 'people#type_select'

end

app/views/layouts/_footer.html.erb
<footer id="myFooter">
		<div class="container">
				<div class="row">
						<div class="col-sm-12 myCols">
								<h5>Get started</h5>
								<ul>
										<li><%= link_to 'Home', root_path %></li>
										<% if !user_signed_in? %>
										<li><%= link_to 'Sign Up', new_user_registration_path %></li>
										<% end %>
										<!-- <li><%= link_to 'Add a Person', new_person_path %></li>
										<li><%= link_to 'Add a new group', new_group_path %></li> -->
								</ul>
						</div>

						<!-- <div class="col-sm-3 myCols">
								<h5>About us</h5>
								<ul>
										<li><a href="#">Company Information</a></li>
										<li><a href="#">Contact us</a></li>
										<li><a href="#">Reviews</a></li>
								</ul>
						</div>
						<div class="col-sm-3 myCols">
								<h5>Support</h5>
								<ul>
										<li><a href="#">FAQ</a></li>
										<li><a href="#">Help desk</a></li>
										<li><a href="#">Forums</a></li>
								</ul>
						</div>
						<div class="col-sm-3 myCols">
								<h5>Legal</h5>
								<ul>
										<li><a href="#">Terms of Service</a></li>
										<li><a href="#">Terms of Use</a></li>
										<li><a href="#">Privacy Policy</a></li>
								</ul>
						</div> -->
				</div>
		</div>
		<div class="social-networks">
				<a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
				<a href="#" class="facebook"><i class="fa fa-facebook-official"></i></a>
				<a href="#" class="google"><i class="fa fa-google-plus"></i></a>
		</div>
		<div class="footer-copyright">
				<p>Copyright &copy; 2017 | <a href="http://www.planetome.com">Planetome Inc.</a>
					by Roman Mishiev.</p>
		</div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

app/views/layouts/_messages.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name} fade in" %>' role="alert">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-white">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo_startups_space.png',style: 'height:80%;width:auto;margin-top:3px;'), root_path, class: "navbar-brand img-responsive", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">///<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Cities', categories_path %></li>
            <li><%= link_to "People", people_path %></li>
            <li><%= link_to 'Groups', groups_path %></li>
          </ul>
        </li>
<!--
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Create a new person', new_person_path %></li>
                <li><%= link_to 'Create a new group', new_group_path %></li>
              </ul>
            </li>
            <% end %> -->

            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Cities', categories_path %></li>
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
                <% end %>
                <% if user_signed_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create new Category", new_category_path %></li>
                <% end %>

              </ul>
            </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left hidden-md hidden-sm">
        <div class="form-group">


        </div>

      </form> -->
      <ul class="nav navbar-nav navbar-right">
            <!-- <li id="nav-guest" ><a href="#">Find a Trip</a></li> -->


            <!-- <% if user_signed_in? %>
            <li id="nav-host"><span class="label label-info label-host"><%= link_to 'Add a Person', new_person_path %></span></li>
            <% end %> -->


            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your <%= "admin" if current_user.admin? %> profile<span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <% if current_user  %>
                <div class="row">
                  <div class="col-md-5">
                    <li class="navimage">

                      <% if current_user.avatar?  %>
                      <%= image_tag current_user.avatar.url(:thumb), class: "profilePhotoThumb" %>
                      <% else %>
                      <%= gravatar_for current_user, size: 20 %></li>
                      <% end %>



                  </div>
                  <div class="col-md-7 ">
                    <li class="navname"><%= current_user.name %></li>
                  </div>
                </div>

                <% end %>
                <li role="separator" class="divider"></li>

                <li><%= link_to 'View your public profile', user_path(current_user)%></li>
                <li role="separator" class="divider"></li>

                <li><%= link_to 'Edit your profile', edit_user_path(current_user)%></li>
                <li><%= link_to 'Edit password & email', edit_user_registration_path(current_user)%></li>
                <li role="separator" class="divider"></li>

                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>

          <li><%= link_to  new_user_session_path do %>
            <p id="p-margin-b-0" ><span class="glyphicon glyphicon-log-in"></span> Log In</p><% end %></li>
          <li><%= link_to  new_user_registration_path do %>
            <p id="p-margin-b-0" ><span class="glyphicon glyphicon-pencil"></span> Sign Up</p><% end %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet" type="text/css" />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="assets/stylesheet/footer.css">
    <link rel="stylesheet" href="assets/stylesheet/custom.css.scss">
    <!-- <link href="./assets/css/bootstrap.min.css" rel="stylesheet" /> -->
    <!-- <link href="assets/css/now-ui-kit.css" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="assets/css/now-ui-kit.css"> -->


    <!-- <link rel="stylesheet" href="awesomplete.css" />
    <script src="awesomplete.js" async></script> -->
  </head>

  <body id="show-listing-body">
    <div class="container-fluid">
    <%= render 'layouts/navigation' %>
  </div>

    <div class="container-fluid">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
      <!-- <%= debug(params) if Rails.env.development? %> -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>

    <%= render 'layouts/footer' %>

</html>